version: '3.8'

services:
  spring-app:
    image: inheecho/consumer-v1  # Spring Boot 애플리케이션 이미지
    container_name: spring-app-consumer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - spring-net
    volumes:
      - /home/ec2-user/logs:/logs

#  redis:
#    image: redis:latest
#    container_name: redis-container
#    depends_on:
#      - spring-app
#    ports:
#      - "6379:6379"
#    networks:
#      - spring-net

networks:
  spring-net:
    driver: bridge
volumes:
  logs: